.TH gmanedit 1 "26 Feb 2008" "GNOME manpage editor"

.SH NAME
gmanedit \-man pages editor

.SH SYNOPSIS
.B gmanedit

.SH DESCRIPTION
.B Gmanedit
helps you to write your application manual pages on a simple way. 
You need know the manpages format. You can learn it from man(7).
.PP

.SH LICENSE
Copyright (C) 2000 Sergio Rua <email unknown>,
Copyright (C) 2008 Joop Stakenborg <pg4i@amsat.org>

This program is licensed under the GNU General Public License version 2.

.SH BUGS
Report bugs to the code maintainer. Thank you.

