.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH gmanedit 1 "March 10, 2008" "" "Gnome manpages editor"

.SH NAME
gmanedit \- GTK+ program for editing manual pages.

.SH SYNOPSIS
.B gmanedit 
[
.I filename
]

.SH DESCRIPTION
.B gmanedit
can be used to edit existing manual pages or create new pages with the
help of a wizard. Created pages can be viewed with the help of an external
application.

.SH BUGS
Report bugs to the Joop Stakenborg <pg4i@amsat.org>
